GO
PRINT "------ EXECUTING SQL STETUP SCRIPT ------"
PRINT ""
PRINT "------ SETTING UP TRIGGER ------"
PRINT ""
GO
CREATE TRIGGER trg_alter_login ON ALL SERVER
FOR ALTER_LOGIN
AS
    IF ORIGINAL_LOGIN() = '$(SANDBOX_USERNAME)'
    Begin   
        RAISERROR(N'Password change is not allowed here', 10, 1);
        ROLLBACK
    end
GO
PRINT "------ DONE SETTING UP TRIGGER ------"
PRINT ""

PRINT "------ RESTORING $(DEMO_BACKUP_NAME) ------"
PRINT ""
GO
RESTORE DATABASE $(SANDBOX_DB) FROM DISK = '$(DEMO_BACKUP_FILENAME)'
WITH REPLACE, FILE = 1,
    MOVE N'$(DEMO_BACKUP_NAME)' TO N'$(DEMO_BACKUP_NAME_MDF_PATH)',
    MOVE N'$(DEMO_BACKUP_NAME_LOG)' TO  N'$(DEMO_BACKUP_NAME_LOG_PATH)'
GO
USE master
GO
PRINT "------ CONFIGURING $(DEMO_BACKUP_NAME) ------"
PRINT ""
GO
sp_configure 'contained database authentication', 1
GO 
RECONFIGURE;
GO  
ALTER DATABASE $(SANDBOX_DB) SET CONTAINMENT = PARTIAL;
GO
USE $(SANDBOX_DB)
GO
PRINT "------ CREATING SANDBOX USER ------"
PRINT ""
GO
CREATE LOGIN $(SANDBOX_USERNAME) WITH PASSWORD = '$(SANDBOX_PASSWORD)';
GO
CREATE USER $(SANDBOX_USERNAME) FOR LOGIN $(SANDBOX_USERNAME);
GO
GRANT SELECT, INSERT, UPDATE TO $(SANDBOX_USERNAME);
GO
DENY CREATE TABLE, BACKUP DATABASE, BACKUP LOG, CREATE FUNCTION, CREATE PROCEDURE, CREATE RULE TO $(SANDBOX_USERNAME);
GO
USE master
GO
PRINT "------ CREATING SQL PLAYGROUND ------"
PRINT ""
GO
CREATE DATABASE Playground
GO
USE Playground
GO
CREATE USER $(SANDBOX_USERNAME) FOR LOGIN $(SANDBOX_USERNAME);
GO
GRANT ALTER, INSERT, SELECT, UPDATE TO $(SANDBOX_USERNAME);
GO
DENY DELETE, BACKUP DATABASE, BACKUP LOG, CREATE FUNCTION, CREATE PROCEDURE, CREATE SCHEMA, CREATE RULE TO $(SANDBOX_USERNAME);
GO
PRINT "------ DONE ------"
PRINT ""
GO