USE master
GO
sp_configure 'contained database authentication', 1;  
GO  
RECONFIGURE
GO  
CREATE TRIGGER trg_alter_login ON ALL SERVER
FOR ALTER_LOGIN
AS
    IF ORIGINAL_LOGIN() = '$(SANDBOX_USERNAME)'
    Begin   
        RAISERROR(N'Password change is not allowed here', 10, 1);
        ROLLBACK
    end
GO
RESTORE DATABASE $(SANDBOX_DB) FROM DISK = '$(DEMO_BACKUP_FILENAME)'
WITH REPLACE, FILE = 1,
    MOVE N'$(DEMO_BACKUP_NAME)' TO N'$(DEMO_BACKUP_NAME_MDF_PATH)',
    MOVE N'$(DEMO_BACKUP_NAME_LOG)' TO  N'$(DEMO_BACKUP_NAME_LOG_PATH)'
GO
ALTER DATABASE $(SANDBOX_DB) SET CONTAINMENT = PARTIAL
GO
USE $(SANDBOX_DB)
GO
CREATE LOGIN $(SANDBOX_USERNAME) WITH PASSWORD = '$(SANDBOX_PASSWORD)';
CREATE USER $(SANDBOX_USERNAME) FOR LOGIN $(SANDBOX_USERNAME);
GRANT SELECT, INSERT, UPDATE TO $(SANDBOX_USERNAME);
DENY CREATE TABLE, BACKUP DATABASE, BACKUP LOG, CREATE FUNCTION, CREATE PROCEDURE, CREATE RULE TO $(SANDBOX_USERNAME);
GO
USE master
GO
CREATE DATABASE Playground
GO
USE Playground
GO
CREATE USER $(SANDBOX_USERNAME) FOR LOGIN $(SANDBOX_USERNAME);
GRANT ALTER, SELECT, UPDATE TO $(SANDBOX_USERNAME);
DENY DELETE, BACKUP DATABASE, BACKUP LOG, CREATE FUNCTION, CREATE PROCEDURE, CREATE SCHEMA, CREATE RULE TO $(SANDBOX_USERNAME);
GO




